bucket          = "home-dev-tf-state"
key             = "home-prod-bootstrap"
region          = "us-east-1"
dynamodb_table  = "home-dev-tf-state-lock"
role_arn        = ""
profile         = "clarence"
suffix          = "prod"