apiVersion: v1
kind: PersistentVolume
metadata:
  name: ltc-pv
spec:
  capacity:
    storage: 10Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-06c3f6f30b73ec9c4
