apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: ltc
spec:
  selector:
    matchLabels:
      app: ltc 
  serviceName: ltc
  replicas: 1
  template:
    metadata:
      labels:
        app: ltc
    spec:
      containers:
        - name: ltc 
          image: "jbeaudry-litecoin:latest"
          imagePullPolicy: "Never"
          command: ["litecoind"]
          args: ["-printtoconsole", "-disablewallet", "-maxuploadtarget=7500"]
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts: 
            - name: localvolume
              mountPath: "/home/worker/.litecoin"
      volumes:
        - name: localvolume
          persistentVolumeClaim:
            claimName: ltc-pvc